### ISSUE TITLE
Found Issue, Going Next Course Message: Script Timeout

### ISSUE THREAD

**Issue by BoostUpStation** [anilabhadatta/educative.io_scraper#13] opened 2022-07-23 03:05 UTC
How to increase script timeout?
 so that the scraper doesn't goto next course without completing previous one.

if you don't wamt to implement it here, then please tell me, i'll do in my local script.

**Comment by anilabhadatta** [comment] 2022-07-23 08:54
@BoostUpStation actually i have given a lot of sleep commands and the scraping happens sequentially. there is a wait_webdriver function where you can increase the sleeping time to load the page but i am seeing Script timeout error for the first time. Do you have the output before you received this error message, then i can understand in which function the scraper was running before termination.

**Comment by anilabhadatta** [comment] 2022-07-23 09:02
@BoostUpStation you can put some print statements to see if the page has loaded properly or not.
![image](https://user-images.githubusercontent.com/48487849/180598290-f6dcbc4f-d719-420b-b332-d603396708b3.png)

I need some more info for that error message, mainly the last function accessed by the scraper

**Comment by BoostUpStation** [comment] 2022-07-23 10:38
@anilabhadatta the scraper was running in 'get_pagecontent_using_Singlefile' function.
It terminated there.
And didn't printed 'html file created'

**Comment by anilabhadatta** [comment] 2022-07-23 12:11
@BoostUpStation i dont think it can be fixed because this issue is caused by single file.
Single file function basically gets the content and it is a async function so it will return only when the content is retrieved.
Maybe the page suffered some issues for which single file took a lot of time but couldn't get the content.
Restarting should fix this issue, and maybe it is happening due to low page loading time (slow internet maybe) or chrome overloaded.
You can also try injecting singlefile js from local directory but i am not sure if it will fix this issue.

**Comment by BoostUpStation** [comment] 2022-07-23 13:51
@anilabhadatta 
Some times this issue occur and sometimes not.
I tried to locally inject the script and nothing worked :(
may you please try it if possible?
Or any way to directly add the script to the scraper?

**Comment by anilabhadatta** [comment] 2022-07-23 15:32
@BoostUpStation check the singlefile repo for fixing this issue and you can reduce some parameters in the command. Block videos audios and script parameters are necessary

**Comment by anilabhadatta** [comment] 2022-07-23 18:41
@BoostUpStation try these settings

![image](https://user-images.githubusercontent.com/48487849/180618689-d53b0934-4566-4199-8192-6de5266e4149.png)

**Comment by BoostUpStation** [comment] 2022-07-23 19:56
@anilabhadatta ok, i'll try that.
But whats the use already present 'title, filename' in those curly braces?

**Comment by anilabhadatta** [comment] 2022-07-23 20:00
@BoostUpStation single file creates a default title and filename from the HTML, maybe for those it is causing the async funct to malfunction. I am not sure, maybe the developer of single-file can explain this issue properly.

**Comment by BoostUpStation** [comment] 2022-07-23 20:10
@anilabhadatta ohk, and as we are only taking the content out, so no need for those variables.
Will try and report by tomorrow eve.
Thanks.

**Comment by BoostUpStation** [comment] 2022-07-23 22:30
@anilabhadatta  still getting the script timeout issue.
Don't know why,
If no fix from your side. Then you may close this issue here itself.
Thanks.

**Comment by anilabhadatta** [comment] 2022-07-23 22:48
@BoostUpStation https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-SingleFile-library-code-in-%22custom%22-environments%3F
read this wiki, maybe it is a cors issue.

**Comment by anilabhadatta** [comment] 2022-07-24 15:21
@BoostUpStation Can you tell me the rate of getting this error in suppose scraping 20 courses?
I think if the page is loaded using the topic URL list, maybe this error won't occur, or it may happen due to the CORS issue. Try using singlefile.init() before the scrap command as stated in that wiki.

**Comment by BoostUpStation** [comment] 2022-07-24 15:52
@anilabhadatta i think the rate is between 5 to 10.
Will try out the init for sure.

**Comment by BoostUpStation** [comment] 2022-07-24 16:30
@anilabhadatta and in that documentation, its saying to pass an object as parameter in init method.
Required? If yes then what to pass? idk

**Comment by anilabhadatta** [comment] 2022-07-24 18:54
@BoostUpStation I don't know yet what to pass.

**Comment by anilabhadatta** [comment] 2022-07-25 17:01
@BoostUpStation Can you send me the url where you faced this issue. You can also talk to the above mentioned issue regarding this.

**Comment by anilabhadatta** [comment] 2022-07-26 07:41
![image](https://user-images.githubusercontent.com/48487849/180951110-1411235d-6498-4ce9-a6f3-58ccb37b2537.png)
@BoostUpStation Also you can try adding networkTimeout: 60000 in both try and except block and see if it fixes.

**Comment by BoostUpStation** [comment] 2022-07-27 17:27
@anilabhadatta i think its working now.
But will try more.
thanks.

**Comment by anilabhadatta** [comment] 2022-07-27 17:35
@BoostUpStation Test it with many courses.
Also check if that "something went wrong" error is still showing . I will try to implement the topic URL traversal after 30th probably and it should fix those issues by a margin.

**Comment by BoostUpStation** [comment] 2022-07-31 22:51
@anilabhadatta the script timeout error has been resolved now.
It was due to network fluctuations. No issues in my wifi at night and neighbours wifi anytime HAHA.

**Comment by anilabhadatta** [comment] 2022-07-31 22:57
@BoostUpStation I will still recommend using try-except block and use networktimeout parameter. I will push the modified code after few minutes.
I am closing the issue as of now.

**Closed by anilabhadatta** 2022-07-31 22:57 UTC
